version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_new
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      - recipe_network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 40s

  app:
    build: .
    container_name: app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - recipe_network
    restart: on-failure:3

networks:
  recipe_network:
    driver: bridge